[project]
name = "ttc-gtfs-rt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gtfs-realtime-bindings>=1.0.0",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]
